language: csharp
dist: xenial
os:
  - linux
  - osx

cache:
  directories:
    - tools
    - src/Cake.Warp/warp
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
git:
  depth: false

branches:
  except:
    - ci/appveyor
    - /^dependabot\/.*/

script:
  - ./build.sh --target=CI
